apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: zipkin
  name: zipkin
  namespace: default
spec:
  type: NodePort
  ports:
  - nodePort: 31001
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    k8s-app: zipkin
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zipkin
  labels:
    k8s-app: zipkin
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: zipkin
    spec:
      containers:
        - name: zipkin
          image: "openzipkin/zipkin:2"
